inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  # デフォルトだと勝手にオンになっているCopがあるので一旦全部切っておく
  DisabledByDefault: true
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/

## `and return` の形式を利用できるようにします。基本的には、&& と || を使います。
Style/AndOr:
  Enabled: false

## 日本語コメントを許可します。
Style/AsciiComments:
  Enabled: false

## 文字列リテラルがデフォルトでfreezeされるようになったので対象外に
Style/FrozenStringLiteralComment:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# 桁揃えが綺麗にならないことが多いので migration は除外
Style/ExtraSpacing:
  Exclude:
    - "db/migrate/*.rb"

# if 文の中に 3 行程度のブロックを書くことを許容
Style/GuardClause:
  MinBodyLength: 5
